# Generated by Django 5.0.7 on 2024-08-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Responden",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=50)),
                ("usia", models.CharField(max_length=25)),
                ("gender", models.CharField(max_length=25)),
                ("etnis", models.CharField(max_length=25)),
                ("pendidikan", models.CharField(max_length=100)),
                ("pekerjaan", models.CharField(max_length=100)),
                ("frk_belanja", models.CharField(max_length=50)),
                ("platform", models.CharField(max_length=100)),
                ("barang", models.CharField(max_length=150)),
                ("range_harga", models.CharField(max_length=50)),
                ("alasan", models.CharField(max_length=100)),
                ("promo_diskon", models.CharField(max_length=50)),
                ("medsos", models.CharField(max_length=50)),
                ("iklan", models.CharField(max_length=50)),
                ("desain", models.CharField(max_length=50)),
                ("fitur_produk", models.CharField(max_length=50)),
                ("pendapatan", models.IntegerField()),
                ("produk_unik", models.IntegerField()),
                ("harga_terjangkau", models.IntegerField()),
                ("promo_diskon_pengaruh", models.IntegerField()),
                ("banding_harga", models.IntegerField()),
                ("rating", models.IntegerField()),
                ("iklan_digital", models.IntegerField()),
                ("campaign_influencer", models.IntegerField()),
                ("lingkungan", models.IntegerField()),
                ("desain_lebih_penting", models.IntegerField()),
                ("kualitas_desain", models.IntegerField()),
                ("loyal_brand", models.IntegerField()),
                ("keyakinan", models.IntegerField()),
                ("gaya_hidup", models.IntegerField()),
                ("kelas", models.CharField(max_length=50)),
                ("kelas_angka", models.IntegerField()),
            ],
        ),
    ]
