# Generated by Django 5.0.7 on 2024-08-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0002_responden_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="responden",
            name="kelas_angka",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
